wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/resnet18/tools/train_classification_model.py
    python_version: 3.9.15
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688223756.039655
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.15.3
      8:
      - 5
